add "-dynamic" flag to compiler and linker
- This fixes the linker error where there are many undefined
  references around wrap_H5Fclose, wrap_H5Fcreate, wrap_H5Fopen (see
  below).  The warning says that the shared libraries from the
  glibc version used for linking are not available at runtime, so I
  suspect the errors are also because of that.  Although if we're
  linking statically shouldn't those libraries be built into the
  executable (by definition)?  At any rate, the "-dynamic" flag solves
  the problem.

twhilton@cori08:~/Code/Regrid/GEOS-Chem_Regrid> make -f GEOSChem_2_IOAPI.mk clean all
rm -fv   *.o *.mod
removed `GC_bdy_vertical_interp.o'
ftn -O2 -c -C -I/global/homes/t/twhilton/thilton/local/include -I/project/projectdirs/m2319/local/include GEOSChem_2_IOAPI.F90
ftn -openmp -lpthread -o GEOSChem_2_IOAPI.exe GEOSChem_2_IOAPI.o \
        -L/project/projectdirs/m2319/local/lib  -lioapi_regrid_tools -lioapi -lncio -lnetcdf
	/opt/cray/hdf5/1.8.14/INTEL/14.0/lib/libhdf5.a(H5PL.o): In function `H5PL_load':
	H5PL.c:(.text+0x3b7): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
	/opt/cray/netcdf/4.3.3.1/INTEL/14.0/lib/libnetcdf.a(libnetcdf4_la-nc4file.o): In function `close_netcdf4_file':
	/b/ulib/netcdf/4.3.3.1/rpm/BUILD/cray-netcdf-4.3.3.1-intel/netcdf-4.3.3.1/libsrc4/nc4file.c:3027: undefined reference to `__wrap_H5Fclose'
	/opt/cray/netcdf/4.3.3.1/INTEL/14.0/lib/libnetcdf.a(libnetcdf4_la-nc4file.o): In function `nc4_create_file':
	/b/ulib/netcdf/4.3.3.1/rpm/BUILD/cray-netcdf-4.3.3.1-intel/netcdf-4.3.3.1/libsrc4/nc4file.c:389: undefined reference to `__wrap_H5Fcreate'
	/opt/cray/netcdf/4.3.3.1/INTEL/14.0/lib/libnetcdf.a(libnetcdf4_la-nc4file.o): In function `close_netcdf4_file':
	/b/ulib/netcdf/4.3.3.1/rpm/BUILD/cray-netcdf-4.3.3.1-intel/netcdf-4.3.3.1/libsrc4/nc4file.c:3027: undefined reference to `__wrap_H5Fclose'
	/opt/cray/netcdf/4.3.3.1/INTEL/14.0/lib/libnetcdf.a(libnetcdf4_la-nc4file.o): In function `nc4_open_file':
	/b/ulib/netcdf/4.3.3.1/rpm/BUILD/cray-netcdf-4.3.3.1-intel/netcdf-4.3.3.1/libsrc4/nc4file.c:2250: undefined reference to `__wrap_H5Fopen'
	/opt/cray/netcdf/4.3.3.1/INTEL/14.0/lib/libnetcdf.a(libnetcdf4_la-nc4file.o): In function `close_netcdf4_file':
	/b/ulib/netcdf/4.3.3.1/rpm/BUILD/cray-netcdf-4.3.3.1-intel/netcdf-4.3.3.1/libsrc4/nc4file.c:3027: undefined reference to `__wrap_H5Fclose'
	/b/ulib/netcdf/4.3.3.1/rpm/BUILD/cray-netcdf-4.3.3.1-intel/netcdf-4.3.3.1/libsrc4/nc4file.c:3027: undefined reference to `__wrap_H5Fclose'
	/opt/cray/hdf5/1.8.14/INTEL/14.0/lib/libhdf5_hl.a(H5LT.o): In function `H5LTopen_file_image':
	H5LT.c:(.text+0xfe8): undefined reference to `__wrap_H5Fopen'
	make: *** [GEOSChem_2_IOAPI.exe] Error 1